# Generated by Django 3.2 on 2021-04-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='comp_type',
            field=models.CharField(choices=[('dev', 'Software Development'), ('gov', 'Government'), ('fin', 'Finance'), ('cos', 'Consulting'), ('ent', 'Entrepreneur'), ('adv', 'Advertising'), ('gde', 'Graphic Design'), ('ani', 'Animation'), ('dsi', 'Data Science'), ('cju', 'Criminal Justice'), ('ecn', 'Economics'), ('con', 'Conservation'), ('ide', 'Interior Design'), (None, 'Undecided')], default=None, max_length=3),
        ),
    ]
